// Generated by gencpp from file chjk/unit_cmd.msg
// DO NOT EDIT!


#ifndef CHJK_MESSAGE_UNIT_CMD_H
#define CHJK_MESSAGE_UNIT_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chjk
{
template <class ContainerAllocator>
struct unit_cmd_
{
  typedef unit_cmd_<ContainerAllocator> Type;

  unit_cmd_()
    : vel(0.0)
    , deg(0.0)  {
    }
  unit_cmd_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , deg(0.0)  {
  (void)_alloc;
    }



   typedef double _vel_type;
  _vel_type vel;

   typedef double _deg_type;
  _deg_type deg;





  typedef boost::shared_ptr< ::chjk::unit_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chjk::unit_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct unit_cmd_

typedef ::chjk::unit_cmd_<std::allocator<void> > unit_cmd;

typedef boost::shared_ptr< ::chjk::unit_cmd > unit_cmdPtr;
typedef boost::shared_ptr< ::chjk::unit_cmd const> unit_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chjk::unit_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chjk::unit_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chjk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'chjk': ['/home/ando/Chojyuku/src/chjk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chjk::unit_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chjk::unit_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chjk::unit_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chjk::unit_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chjk::unit_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chjk::unit_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chjk::unit_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68a821851e17ec6fee5da92fea03d8fc";
  }

  static const char* value(const ::chjk::unit_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68a821851e17ec6fULL;
  static const uint64_t static_value2 = 0xee5da92fea03d8fcULL;
};

template<class ContainerAllocator>
struct DataType< ::chjk::unit_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chjk/unit_cmd";
  }

  static const char* value(const ::chjk::unit_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chjk::unit_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vel\n\
float64 deg\n\
";
  }

  static const char* value(const ::chjk::unit_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chjk::unit_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct unit_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chjk::unit_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chjk::unit_cmd_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "deg: ";
    Printer<double>::stream(s, indent + "  ", v.deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHJK_MESSAGE_UNIT_CMD_H
