// Generated by gencpp from file chjk/vw_cmd.msg
// DO NOT EDIT!


#ifndef CHJK_MESSAGE_VW_CMD_H
#define CHJK_MESSAGE_VW_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chjk
{
template <class ContainerAllocator>
struct vw_cmd_
{
  typedef vw_cmd_<ContainerAllocator> Type;

  vw_cmd_()
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }
  vw_cmd_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::chjk::vw_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chjk::vw_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct vw_cmd_

typedef ::chjk::vw_cmd_<std::allocator<void> > vw_cmd;

typedef boost::shared_ptr< ::chjk::vw_cmd > vw_cmdPtr;
typedef boost::shared_ptr< ::chjk::vw_cmd const> vw_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chjk::vw_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chjk::vw_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chjk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'chjk': ['/home/ando/Chojyuku/src/chjk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chjk::vw_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chjk::vw_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chjk::vw_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chjk::vw_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chjk::vw_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chjk::vw_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chjk::vw_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "461e74593b26c77a7c97f00fe82c6d79";
  }

  static const char* value(const ::chjk::vw_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x461e74593b26c77aULL;
  static const uint64_t static_value2 = 0x7c97f00fe82c6d79ULL;
};

template<class ContainerAllocator>
struct DataType< ::chjk::vw_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chjk/vw_cmd";
  }

  static const char* value(const ::chjk::vw_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chjk::vw_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n\
float64 vy\n\
float64 w\n\
";
  }

  static const char* value(const ::chjk::vw_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chjk::vw_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vw_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chjk::vw_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chjk::vw_cmd_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHJK_MESSAGE_VW_CMD_H
